<?php
use app\models\Model;

class Cart extends Model
{
    public $id;
    public $good;
    public $price;
    public $producer;

    /**
     * Метод для
     *
     * @return mixed
     */
    protected function getTableName():string
    {
        return 'cart';
    }
    public function getAll()
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }
}